#!/usr/bin/python

from __future__ import print_function

def format_obj(name, verts, normals, faces):
    str = "# Model: %s\n\n" % name

    str += "# This autogenerated model is in the Wavefront .obj file format.\n"
    str += "# See: https://en.wikipedia.org/wiki/Wavefront_.obj_file\n\n"

    str += "# List of vertices (x, y, z, [w]):\n"
    for (x, y, z) in verts:
        str += "v {: .6f} {: .6f} {: .6f}\n".format(x, y, z)

    str += "\n# List of vertex normals (x, y, z):\n"
    for (x, y, z) in normals:
        str += "vn {: .6f} {: .6f} {: .6f}\n".format(x, y, z)

    str += "\n# List of faces (v1, v2, v3) in CCW order:\n"
    for (i1, i2, i3) in faces:
        str += "f {:d}//{:d} {:d}//{:d} {:d}//{:d}\n".format(i1+1, i1+1, i2+1, i2+1, i3+1, i3+1)

    return str

if __name__ == '__main__':
    print("hi")
